server:
  port: ${PORT:5001}

logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:h2:./hexlet
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  rabbitmq:
    port: 5600
